from datetime import datetime, timezone


def format_report_timestamp(value):
    if value is None:
        return "Unknown"
    return str(value)


def format_pdf_timestamp(value):
    if value is None:
        return "Unknown"

    if isinstance(value, datetime):
        dt = value
    else:
        try:
            dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except ValueError:
            return str(value)

    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)

    return dt.strftime("%B %d, %Y · %H:%M UTC")


def format_csv_timestamp(value):
    if value is None:
        return ""

    if isinstance(value, datetime):
        dt = value
    else:
        try:
            dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except ValueError:
            return str(value)

    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)

    return dt.strftime("%Y-%m-%d %H:%M UTC")


def format_display_value(value):
    if value in (None, ""):
        return "Unknown"

    text = str(value).strip()
    if not text:
        return "Unknown"

    explicit_map = {
        "flag_high_priority": "Flag High Priority",
        "block_ip": "Block IP",
        "monitor": "Monitor",
        "executed": "Executed",
        "pending": "Pending",
        "failed": "Failed",
        "open": "Open",
        "resolved": "Resolved",
        "not set": "Not Set",
    }

    lowered = text.lower()
    if lowered in explicit_map:
        return explicit_map[lowered]

    return text.replace("_", " ").title()


def build_alert_summary(alert_type):
    summary_map = {
        "failed_login_threshold": "Multiple failed login attempts were grouped into a threshold alert, indicating likely credential abuse or password guessing activity.",
        "port_scan_threshold": "Repeated port scan activity was observed from the same source, suggesting reconnaissance against exposed services.",
        "failed_login": "A failed authentication event was detected and surfaced for analyst review.",
        "login_failure": "A login failure event was detected and surfaced for analyst review.",
        "port_scan": "A port scanning event was detected and surfaced for analyst review.",
        "normal_activity": "This alert reflects activity recorded by the platform that may require analyst validation based on surrounding context.",
    }
    return summary_map.get(
        alert_type,
        f"This incident report covers a {alert_type} alert generated by the SIEM and summarizes the available evidence for analyst review.",
    )


def build_severity_explanation(severity):
    severity_explanations = {
        "low": "Low severity indicates limited immediate risk. The event should be documented and monitored for changes or recurrence.",
        "medium": "Medium severity indicates suspicious activity that warrants analyst review and possible containment if supporting evidence increases.",
        "high": "High severity indicates elevated risk and likely malicious behavior requiring prompt investigation and response.",
        "critical": "Critical severity indicates urgent risk with likely active compromise or major impact, requiring immediate containment and escalation.",
    }
    return severity_explanations.get(
        severity,
        "Severity was not recognized. Review the alert context and supporting telemetry directly."
    )


def build_confidence_level(severity):
    if severity == "low":
        return "Low"
    if severity == "medium":
        return "Medium"
    if severity in {"high", "critical"}:
        return "High"
    return "Unknown"


def build_next_steps(alert_type):
    next_steps_map = {
        "failed_login_threshold": [
            "Validate whether the targeted account experienced additional authentication failures or a lockout condition.",
            "Correlate the source IP with firewall, reverse proxy, or identity provider logs for repeated access attempts.",
            "Consider blocking or rate-limiting the source if the activity is confirmed malicious.",
        ],
        "port_scan_threshold": [
            "Review exposed services and confirm whether the probed ports were expected to be reachable.",
            "Correlate the source IP with network telemetry to determine scan breadth and duration.",
            "Consider blocking the source and validating there was no follow-on exploitation activity.",
        ],
    }
    return next_steps_map.get(
        alert_type,
        [
            "Review surrounding SIEM events for related indicators from the same source.",
            "Confirm whether the observed activity matches expected behavior for the environment.",
            "Document analyst findings and escalate if additional malicious evidence is found.",
        ],
    )
